app.config(['$routeProvider',function($routeProvider){
		$routeProvider.when('/',{
			templateUrl:'pages/login/denglu/denglu.html',
			controller:'dengluCtrl'
		}).when('/xgmm',{
			templateUrl:'pages/login/xgmm/xgmm.html',
			controller:'xgmmCtrl'
		}).when('/zhmm',{
			templateUrl:'pages/login/zhmm/zhmm.html',
			controller:'zhmmCtrl'
		}).when('/zuche',{
			templateUrl:'pages/login/zuche/zuche.html',
			controller:'zucheCtrl'
		}).when('/read',{
			templateUrl:'pages/reading/read/read.html',
			controller:'readCtrl'
		}).when('/mulu',{
			templateUrl:'pages/reading/mulu/mulu.html',
			controller:'muluCtrl'
		}).when('/shuqian',{
			templateUrl:'pages/reading/shuqian/shuqian.html',
			controller:'shuqianCtrl'
		}).when('/biji',{
			templateUrl:'pages/reading/biji/biji.html',
			controller:'bijiCtrl'
		}).when('/readDetail',{
			templateUrl:'pages/reading/readDetail/readDetail.html',
			controller:'readDetailCtrl'
		}).when('/mynote',{
			templateUrl:'pages/reading/mynote/mynote.html',
			controller:'mynoteCtrl'
		}).when('/binding',{
			templateUrl:'pages/my/binding/binding.html',
			controller:'bindingCtrl'
		}).when('/myself',{
			templateUrl:'pages/my/myself/myself.html',
			controller:'myselfCtrl'
		}).when('/shezhi',{
			templateUrl:'pages/my/shezhi/shezhi.html',
			controller:'shezhiCtrl'
		}).when('/copyright',{
			templateUrl:'pages/my/copyright/copyright.html',
			controller:'copyrightCtrl'
		}).when('/like',{
			templateUrl:'pages/my/like/like.html',
			controller:'likeCtrl'
		}).when('/my',{
			templateUrl:'pages/my/my/my.html',
			controller:'myCtrl'
		}).when('/myprofile',{
			templateUrl:'pages/my/myprofile/myprofile.html',
			controller:'myprofileCtrl'
		}).when('/setpassword',{
			templateUrl:'pages/my/setpassword/setpassword.html',
			controller:'setpasswordCtrl'
		}).when('/yijian',{
			templateUrl:'pages/my/yijian/yijian.html',
			controller:'yijianCtrl'
		})
	}	
])
